### ISSUE TITLE
Improve login page

### ISSUE THREAD

**Issue by hunter** [AcalephStorage/kontinuous-ui#14]
The Github button currently used on the login page is not clear enough. A small login container in the centre of the page with branding and explanation would help (perhaps something similar to the Auth0 login)

**Comment by stefanymarie** [comment]
<img width="561" alt="login-page" src="https://cloud.githubusercontent.com/assets/582535/15565450/61c05350-234d-11e6-9ad4-37ecd0a53c92.png">

**Comment by hunter** [comment]
👍
