### ISSUE TITLE
Improvements from v0.1.1

### ISSUE THREAD

**Issue by stefanymarie** [AcalephStorage/kontinuous-ui#15]
Enhancements
- [x] Use [Ace](https://github.com/ajaxorg/ace) Editor for editing pipeline definition
- [x] Modify loading indicator for pages
- [x] Fetch logs when stage status changes from `PENDING` to `RUNNING` while the info-box for stage details is open

Bugs
- [x] Fix info box overlapping modal for "Trigger Pipeline" confirmation
- [ ] Add author name when user triggers pipeline from dashboard (needs API changes)

**Comment by stefanymarie** [comment]
- Add author name when user triggers pipeline from dashboard (needs API changes)
  - kontinuous API endpoint `/login/github` has to return the `user_name` of the authorized github user (rel. [82c15f5](https://github.com/AcalephStorage/kontinuous-ui/blob/82c15f5acc1e2b41124f82a0de918073471a81ae/app/torii-providers/github-kontinuous.js#L38))

**Comment by hunter** [comment]
Assigning to @darkcrux for adding user details in the refactor

**Comment by darkcrux** [comment]
the improvements for v0.1.1 have already been merged. I'll open a  new ticket for the user/pipeline changes.
