### ISSUE TITLE
Build popup scrolling

### ISSUE THREAD

**Issue by hunter** [AcalephStorage/kontinuous-ui#18]
It's quite confusing to have the whole build popup scrolling so that the title and close button are lost.

We either need to keep the title and close button visible at all times or only scroll the log. My preference would be the latter but that may depend on screen height?

**Comment by stefanymarie** [comment]
Hmm.. I think the first option is better because this will not limit the height of the logs display.
For the second option, we have to set a min-height (calculate based on height of the info box) for the logs display, which may turn out to be small.

**Comment by hunter** [comment]
My preference would still be for the second option (although I'd think we'd probably need to change the details into two columns to reduce the height)

Another alternative to consider is an Accordion that combines the details and each log into different panes.

**Comment by stefanymarie** [comment]
Ok. I'll also checkout accordion and see how it'll look.

**Comment by stefanymarie** [comment]
1- the accordion looks complicated (wrt max-height computation), but here's a preview (manual height manipulation)
<img width="780" alt="18-accordion" src="https://cloud.githubusercontent.com/assets/582535/15665718/3377d96e-273f-11e6-93f2-5da28b11d5d0.png">
2- will try minimizing the height of the details table,
3- but here's another idea (kinda like weavescope's)
<img width="775" alt="18-menu" src="https://cloud.githubusercontent.com/assets/582535/15666009/eb17eb9e-2740-11e6-8357-6dc120ceb1fc.png">
<img width="1398" alt="18-weave-scope-idea" src="https://cloud.githubusercontent.com/assets/582535/15666011/ed6f4702-2740-11e6-8bcd-db33f8e82dee.png">

**Comment by hunter** [comment]
Not bad. What is the computer monitor icon for? Details?

**Comment by stefanymarie** [comment]
Yes, Details.

**Comment by hunter** [comment]
The icon isn't that clear as the only element. I'd say just use "Details" and implement

**Comment by stefanymarie** [comment]
👍

**Comment by stefanymarie** [comment]
included in release [v0.1.2](https://github.com/AcalephStorage/kontinuous-ui/releases/tag/0.1.2)
