### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by hunter** [AcalephStorage/kontinuous-ui#20]
Since we're handling credentials, SSL will need to be enabled (ideally with HTTP/2)

**Comment by stefanymarie** [comment]
PR: #21 
- configure Caddy tls (https://caddyserver.com/docs/tls)
- add SSL cert & key as k8s Secret (ssl-secret)
- mount ssl-secret as volume in container to /secrets/ssl (http://kubernetes.io/docs/user-guide/secrets/#consuming-secret-values-from-volumes)

**Comment by hunter** [comment]
Nicely done! Lets do the same for Kontinuous. Will the JS handle https and self signed certs?

**Comment by stefanymarie** [comment]
Caddy will handle https and we have to generate the cert & key and store it in a Secret

**Comment by hunter** [comment]
Sorry, I should have been more clear. Will our JS code have any issues in connecting to the Kontinuous API if its running https and handling a self-signed cert. Have we hardcoded any URLs in there and can the AJAX requests be configured to ignore invalid certs (by an ENV var)?

**Comment by darkcrux** [comment]
kontinuous [PR#61](https://github.com/AcalephStorage/kontinuous/pull/61/files) for http2 and ssl support for kontinuous. i don't think there are hard coded URLs but the hooks may need to be tested too.

**Comment by stefanymarie** [comment]
There are no hardcoded URLs. But, yeah, I got `net::ERR_INSECURE_RESPONSE` accessing the API. Will work on it.

**Comment by darkcrux** [comment]
This seems to have the same limitation we have with the k8s dashboard. We were able to access the dashboard and the api by accepting the warning on the browser for both endpoint. The only work around I can think of is adding the certificate authority to the keychain and preventing the warning.

**Comment by hunter** [comment]
Letsencrypt would get around it but will require a hostname to be assigned (which we should support)

Otherwise, using the same self signed SSL cert for both front and backend as a hacky workaround?

**Comment by darkcrux** [comment]
i wonder if that works. worth a try.
