### ISSUE TITLE
Polling

### ISSUE THREAD

**Issue by hunter** [AcalephStorage/kontinuous-ui#6]
Currently the main pipeline and builds page need to be refreshed to update status. A background poll would be useful for keeping track of build status.

**Comment by stefanymarie** [comment]
background polls:
- Pipelines page
  - list of pipelines every `60s`
- Pipeline page
  - builds history every `10s`
  - stage details of the selected build every `5s`
  - logs of the selected stage every `5s`

**Comment by stefanymarie** [comment]
added in [v0.1.1](https://github.com/AcalephStorage/kontinuous-ui/releases/tag/0.1.1)
