### ISSUE TITLE
Show build in progress indicator

### ISSUE THREAD

**Issue by hunter** [AcalephStorage/kontinuous-ui#7]
It seems there is no way to tell if a build is running. Should show a spinner or bg animation for the current build step.

**Comment by stefanymarie** [comment]
![glow2](https://cloud.githubusercontent.com/assets/582535/15205135/5e110c7e-1847-11e6-85ad-eb33e8362634.gif)

will something like this work?

**Comment by hunter** [comment]
Not bad!

How about No. 5 here? http://tobiasahlin.com/spinkit/ ;)

**Comment by stefanymarie** [comment]
![glow3](https://cloud.githubusercontent.com/assets/582535/15217016/35e7176c-188c-11e6-93ec-5d954666e1b5.gif)
here's how it'll look like

**Comment by stefanymarie** [comment]
fixed in [v0.1.1](https://github.com/AcalephStorage/kontinuous-ui/releases/tag/0.1.1)
