### ISSUE TITLE
Pipeline builder

### ISSUE THREAD

**Issue by hunter** [AcalephStorage/kontinuous-ui#9]
Currently the pipeline is managed by the `.pipeline.yml` that is edited by hand in the repo. We should add an editor to the UI to make it easier to create.

**Comment by stefanymarie** [comment]
initial form fields and data format to be sent to the API

```
name: "textInput:string"                      // (required) metadata.name, spec.selector.matchLabels.app, spec.template.metadata.name 
namespace: "textInput:string"                 // (required) metadata.namespace
metadata:                                     // (optional) spec.template.metadata.labels
  "textInput:string": "textInput:string"
notif:                                        // (optional) spec.template.notif
  - type: "textInput:string"
    // if type is 'slack'
    metadata:                                 // (required)
      username: "textInput:string"            // (required)
      url: "textInput:string"                 // (required)
      channel: "textInput:string"             // (required)
    secret: <dropdown:string>                 // (required)
    // else
    // ?
stages:                                       // (required) spec.template.stages
  - name: "textInput:string"
    type: <dropdown:string>                   // (required)
    params:                                   // (required, or depending on type?)
      "textInput:string": "textInput:string"
    secrets:                                  // (optional)
      - "textInput:string"
```

**Comment by stefanymarie** [comment]
**Work in progress (branches)**
[kontinuous-ui:feature/pipeline-editor](https://github.com/AcalephStorage/kontinuous-ui/commits/feature/pipeline-editor)
[kontinuous:feature/pipeline-editor](https://github.com/AcalephStorage/kontinuous/commits/feature/pipeline-editor)

**Changes**
[kontinuous-ui:https://github.com/AcalephStorage/kontinuous-ui/commit/ac8ed3e135dbdf81b90247ddac00589a1e23b657]
- get `.pipeline.yml` of a pipeline
- commit changes for `.pipeline.yml`

**To Do**
- support the "Pull Request" option (still working on the API)

**Comment by stefanymarie** [comment]
- added Pull Request option.

To commit changes in the definition file, the user can either [1] commit the changes directly to the "default" branch of the repository, or [2] commit the changes to a new branch and start a pull request
